Online_wallet_project/Online_wallet_project/Models/Fee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Online_wallet_project.Models
{
    public class Fee
    {
        public int Id { get; set; }
        public DateTime DateOfStart { get; set; }
        public decimal SumMin { get; set; }
        public decimal SumMax { get; set; }
        public string CalculatingMethod { get; set; }
        public decimal FeeValue { get; set; }
        public DateTime DateOfCreation { get; set; }
        public string CreatorId { get; set; }
        public ApplicationUser Creator  { get; set; }
        public int SupplierId { get; set; }
        public SupplierModel SupplierModel { get; set; }
        public bool IsActive { get; set; }
        public bool Closed { get; set; }
    }
}

Online_wallet_project/Online_wallet_project/Models/SupplierFeeViewModels/DateOfStartSelectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Online_wallet_project.Models.SupplierFeeViewModels
{
    public class DateOfStartSelectViewModel
    {
        [HiddenInput]
        public int SupplierId { get; set; }

        [HiddenInput]
        public bool IsEdited { get; set; }

        [Display(Name = "Дата старта")]
        public DateTime DateOfStart { get; set; }
        
        [HiddenInput]
        public string MethodToRedirect { get; set; }
    }
}

Online_wallet_project/Online_wallet_project/Controllers/FeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Online_wallet_project.Models;
using Online_wallet_project.Models.SupplierFeeViewModels;
using Online_wallet_project.Services.FeeServices;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Online_wallet_project.Controllers
{
    [Authorize(Roles = "Manager")]
    public class FeeController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly FeeServiceContext _feeServiceContext;
        private readonly FeeStatusReportService _feeStatusReportService;
        private readonly TurnOverReportService _turnOverReportService;
        private readonly FeePartReportService _feePartReportService;
        private readonly FeePaidByUserReportService _feePaidByUserReportService;

        [TempData]
        public string Message { get; set; }

        public FeeController(
            UserManager<ApplicationUser> userManager,
            FeeServiceContext feeServiceContext,
            TurnOverReportService turnOverReportService, 
            FeePartReportService feePartReportService, 
            FeePaidByUserReportService feePaidByUserReportService, 
            FeeStatusReportService feeStatusReportService)
        {
            _userManager = userManager;
            _feeServiceContext = feeServiceContext;
            _turnOverReportService = turnOverReportService;
            _feePartReportService = feePartReportService;
            _feePaidByUserReportService = feePaidByUserReportService;
            _feeStatusReportService = feeStatusReportService;
        }

        public async Task<IActionResult> FeeTypeSelect(int supplierId, string message, bool isEdited)
        {           
            var supplier = await _feeServiceContext.GetSupplier(supplierId);
            if (supplier == null)
            {
                return Content("Поставщик не найден");
            }
            _feeServiceContext.SetFeeReportStrategy(_feeStatusReportService);

            SupplierFeeStatusViewModel model = new SupplierFeeStatusViewModel
            {
                SupplierId = supplier.Id,
                Message = message,
                FeeHistoryModel = _feeServiceContext.GetFeeHistoryModel(supplier.Id),
                DateOfStart = DateTime.Today,
                IsEdited = isEdited
            };
            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> FeeTypeSelect(SupplierFeeStatusViewModel model, string feeStatus)
        {
            var supplier = await _feeServiceContext.GetSupplier(model.SupplierId);
            _feeServiceContext.SetFeeReportStrategy(_feeStatusReportService);

            model.FeeHistoryModel = _feeServiceContext.GetFeeHistoryModel(supplier.Id);

            if (model.DateOfStart < DateTime.Now)
            {
                ModelState.AddModelError("", "\"Дата старта\" должна быть больше текущего дня");
                return View(model);
            }

            var creator = await _userManager.GetUserAsync(User);
            if (feeStatus == SupplierFeeStatusModel.NoCommission)
            {
                FeeReportSaveViewModel saveModel = new FeeReportSaveViewModel
                {
                    FeeStatusReportSaveModel = model,
                    Creator = creator
                };
                saveModel.FeeStatusReportSaveModel.SupplierId = supplier.Id;
                saveModel.FeeStatusReportSaveModel.SelectedFeeStatus = SupplierFeeStatusModel.NoCommission;
                await _feeServiceContext.SaveReport(saveModel);

                return RedirectToAction(nameof(CreateSupplierTurnoverReport), 
                    new { supplierId = model.SupplierId, dateOfStart = model.DateOfStart, isEdited = model.IsEdited });
            }
            else if (feeStatus == SupplierFeeStatusModel.YesCommission)
            {
                FeeReportSaveViewModel saveModel = new FeeReportSaveViewModel
                {
                    FeeStatusReportSaveModel = model,
                    Creator = creator
                };
                saveModel.FeeStatusReportSaveModel.SupplierId = supplier.Id;
                saveModel.FeeStatusReportSaveModel.SelectedFeeStatus = SupplierFeeStatusModel.YesCommission;
                await _feeServiceContext.SaveReport(saveModel);

                return RedirectToAction(nameof(CreateSupplierFeePartReport), 
                    new { supplierId = model.SupplierId, dateOfStart = model.DateOfStart, isEdited = model.IsEdited });
            }

            return PartialView("_StatusMassageForAll", "Error:Произошла ошибка");
        }

        #region CreateSupplierTurnoverReport

        public async Task<IActionResult> CreateSupplierTurnoverReport(int supplierId, DateTime dateOfStart, bool isEdited, int reportId)
        {
            var supplier = await _feeServiceContext.GetSupplier(supplierId);
            if (supplier == null)
            {
                return Content("Поставщик не найден");
            }
            _feeServiceContext.SetFeeReportStrategy(_turnOverReportService);

            SupplierTurnoverViewModel model = new SupplierTurnoverViewModel
            {
                Message = Message,
                SupplierId = supplier.Id,
                DateOfStart = dateOfStart,
                FeeHistoryModel = _feeServiceContext.GetFeeHistoryModel(supplier.Id),
            };

            model.FromAmount = await _feeServiceContext.GetFromAmountValue(supplier.Id, model.DateOfStart, isEdited);
            if (isEdited && reportId != 0)
            {
                model.DateOfStart = await _feeServiceContext.GetDateOfStartRewritten(supplier.Id, reportId);
            }
            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateSupplierTurnoverReport(SupplierTurnoverViewModel model, string selectedMethod)
        {
            var supplier = await _feeServiceContext.GetSupplier(model.SupplierId);

            if (selectedMethod == null)
            {
                ModelState.AddModelError("", "Не указан способ подсчета");
                return View();
            }
            _feeServiceContext.SetFeeReportStrategy(_turnOverReportService);

            model.FeeHistoryModel = _feeServiceContext.GetFeeHistoryModel(supplier.Id);

            if (model.SharedValue.Contains("."))
            {
                model.SharedValue = model.SharedValue.Replace('.', ',');
            }
            if (!decimal.TryParse(model.SharedValue, out var x))
            {
                ModelState.AddModelError("", "Попробуйте еще раз ввести долю");
                return View(model);
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.UpToInfinity)
            {
                model.ToAmount = UInt32.MaxValue;
            }
            if (model.ToAmount <= model.FromAmount)
            {
                ModelState.AddModelError("", $"\"Сумма до\" должна быть больше \"Суммы от\"");
                return View(model);
            }
            if (selectedMethod == CalculatingMethodModel.Percent && decimal.Parse(model.SharedValue) <= 0 || 
                selectedMethod == CalculatingMethodModel.Percent && decimal.Parse(model.SharedValue) > 100)
            {
                ModelState.AddModelError("", "Процент должен быть от 1 до 100");
                return View(model);
            }

            var creator = await _userManager.GetUserAsync(User);
            FeeReportSaveViewModel saveModel = new FeeReportSaveViewModel
            {
                TurnoverReportSaveModel = model,
                Creator = creator
            };
            saveModel.TurnoverReportSaveModel.SupplierId = supplier.Id;
            saveModel.SelectedMethod = selectedMethod;
            await _feeServiceContext.SaveReport(saveModel);

            if (model.ToAmount >= UInt32.MaxValue)
            {
                return RedirectToAction(nameof(FullRangeCoverage), 
                    new { supplierId = supplier.Id, feeStatus = SupplierFeeStatusModel.NoCommission});
            }

            Message = "Новая запись по вознаграждению оператора успешно сохранен";

            return RedirectToAction(nameof(CreateSupplierTurnoverReport), 
                new { supplierId = supplier.Id, dateOfStart = model.DateOfStart});
        }

        #endregion

        #region CreateSupplierFeePartReport

        public async Task<IActionResult> CreateSupplierFeePartReport(int supplierId, DateTime dateOfStart, bool isEdited, int reportId)
        {
            var supplier = await _feeServiceContext.GetSupplier(supplierId);
            if (supplier == null)
            {
                return Content("Поставщик не найден");
            }
            _feeServiceContext.SetFeeReportStrategy(_feePartReportService);

            SupplierFeePartViewModel model = new SupplierFeePartViewModel
            {
                FeeHistoryModel = _feeServiceContext.GetFeeHistoryModel(supplier.Id),
                Message = Message,
                SupplierId = supplier.Id,
                DateOfStart = dateOfStart,
                IsEdited = isEdited,
                ReportId = reportId
            };
            if (isEdited && reportId > 0)
            {
                model.DateOfStart = await _feeServiceContext.GetDateOfStartRewritten(supplier.Id, reportId);
            }
            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateSupplierFeePartReport(SupplierFeePartViewModel model, string selectedMethod)
        {
            var supplier = await _feeServiceContext.GetSupplier(model.SupplierId);

Online_wallet_project/Online_wallet_project/Views/Fee/CreateFeePaidByUser.cshtml
@model Online_wallet_project.Models.SupplierFeeViewModels.FeePaidByUserViewModel
@{
    ViewBag.Title = "Создание комиссии для клиента поставщика";
}
@Html.Partial("SupplierInfo", Model.FeeHistoryModel)
<br />
<h3>@ViewBag.Title</h3>
<div class="row">
    <div class="col-md-12 row">
        @Html.Partial("_StatusMessage", Model.Message)
        <form asp-action="CreateFeePaidByUser" method="post" asp-antiforgery="true">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input asp-for="SupplierId" />
            <input asp-for="IsEdited" />
            <input asp-for="FromAmount" type="hidden" />
            <div>
                <div class="col-md-5 form-group-lg">
                    <label asp-for="FromAmount"></label><br />
                    <label class="form-control">@Model.FromAmount</label>
                </div>
                <div id="toAmountValue" class="col-md-5 form-group-lg">
                    <label asp-for="ToAmount"></label>
                    <input type="number" min="0" asp-for="ToAmount" class="form-control" />
                    <span asp-validation-for="ToAmount" class="text-danger"></span>
                </div>
                <div class="col-md-2 form-group-lg">
                    <label asp-for="IsUpToMaxSum"></label>
                    <input id="isUpToMaxSum" type="checkbox" asp-for="IsUpToMaxSum" onchange="SetMaxSumToAmountValue()" />
                </div>
                <br />
                <div>
                    <div class="col-md-12 form-group-lg">
                        <label asp-for="CalcMethodList"></label>
                        @Html.DropDownList("selectedMethod", Model.CalcMethodList, new { @class = "form-control" })
                        <span asp-validation-for="CalcMethodList" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 form-group-lg">
                        <label asp-for="FeeValue"></label>
                        <input type="number" min="0" asp-for="FeeValue" step="0.01" title="Введите числовое значение" class="form-control" />
                        <span asp-validation-for="FeeValue" class="text-danger"></span>
                    </div>
                </div>
                <br />
                <div class="col-md-6 form-group-lg">
                    <label asp-for="DateOfStart"></label><br />
                    <label class="form-control">@Model.DateOfStart.ToShortDateString()</label>
                    <input asp-for="DateOfStart" type="hidden" value="@Model.DateOfStart" />
                </div>
            </div>
            <div class="col-md-offset-9 col-md-3" style="margin-top: 15px">
                <button type="submit" class="btn btn-default btn-group-lg">Сохранить запись</button>
            </div>
        </form>
        <br />
        <div class="col-md-offset-9 col-md-3" style="margin-top: 30px">
            <button type="submit" class="btn btn-default btn-group-lg" onclick="SendExitFromMaster()">Выйти из мастер-формы</button>
        </div>

    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script>
        function SetMaxSumToAmountValue() {
            if ($('#isUpToMaxSum').prop("checked")) {
                $('#toAmountValue').css('visibility', 'hidden');
            }
            else {
                $('#toAmountValue').css('visibility', 'visible');
            }
        }

        function SendExitFromMaster() {
            alert("Чтобы выйти с мастер-формы нужно покрыть весь диапозон до макс. суммы платежа по этому поставщику");
            
        }
    </script>
}

Online_wallet_project/Online_wallet_project/Views/Fee/CreateSupplierFeePartReport.cshtml
@model Online_wallet_project.Models.SupplierFeeViewModels.SupplierFeePartViewModel
@{
    ViewBag.Title = "Создание доли оператора c комиссии";
}
@Html.Partial("SupplierInfo", Model.FeeHistoryModel)
<h3>@ViewBag.Title</h3>
<div class="row">
    <div class="col-md-12 row">
        @Html.Partial("_StatusMessage", Model.Message)
        <form asp-action="CreateSupplierFeePartReport" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input asp-for="SupplierId" />
            <input asp-for="IsEdited" />
            <input asp-for="ReportId" />
            <div>
                <div>
                    <div class="col-md-6 form-group-lg">
                        <label asp-for="CalcMethodList"></label>
                        @Html.DropDownList("selectedMethod", Model.CalcMethodList, new { @class = "form-control" })
                        <span asp-validation-for="CalcMethodList" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 form-group-lg">
                        <label asp-for="SharedValue"></label>
                        <input type="number" min="0" asp-for="SharedValue" step="0.01" title="Введите числовое значениеы" class="form-control" />
                        <span asp-validation-for="SharedValue" class="text-danger"></span>
                    </div>
                </div>
                <br />
                <div class="col-md-6 form-group-lg">
                    <label asp-for="DateOfStart"></label><br />
                    <label class="form-control">@Model.DateOfStart.ToShortDateString()</label>
                    <input asp-for="DateOfStart" type="hidden" value="@Model.DateOfStart" />
                </div>
            </div>
            <div class="col-md-offset-9 col-md-3">
                <button type="submit" class="btn btn-default btn-group-lg">Сохранить запись</button>
            </div>
        </form>
    </div>
</div>
<br/>
<hr/>
@if (Model.IsEdited && Model.ReportId > 0 || Model.IsEdited && Model.ReportId == - 1)
{
    <div class="col-md-offset-10 col-md-2">
        <a asp-action="SupplierCommissionInfo" asp-controller="Fee" asp-route-supplierId="@Model.SupplierId" class="btn btn-default btn-group-lg">
            Выйти
        </a>
    </div>
}
else
{
    <div class="col-md-offset-7" style="display: inline-block; margin-bottom: 40px">
        <form asp-action="CreateFeePaidByUser" asp-controller="Fee" asp-antiforgery="true" method="get">
            <input type="hidden" asp-for="SupplierId" />
            <input type="hidden" asp-for="DateOfStart" />
            <input asp-for="IsEdited" />
            <input type="submit" value="Далее создание комиссии для клиентов поставщика" class="btn btn-default btn-group-lg" />
        </form>
    </div>
}


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Online_wallet_project/Online_wallet_project/Views/Fee/CreateSupplierTurnoverReport.cshtml
@model Online_wallet_project.Models.SupplierFeeViewModels.SupplierTurnoverViewModel
@{
    ViewBag.Title = "Создание вознаграждения оператору при безкомиссионых платежах";
}
@Html.Partial("SupplierInfo", Model.FeeHistoryModel)
<h3>@ViewBag.Title</h3>
<div class="col-md-12 row">
    @Html.Partial("_StatusMessage", Model.Message)

    <form asp-action="CreateSupplierTurnoverReport" method="post" asp-antiforgery="true">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input asp-for="SupplierId" />
        <input asp-for="FromAmount" type="hidden" />
        <div class="row">
            <div class="col-md-5 form-group-lg">
                <label asp-for="FromAmount"></label><br />
                <label class="form-control">@Model.FromAmount</label>
            </div>
            <div id="toAmountValue" class="col-md-5 form-group-lg">
                <label asp-for="ToAmount"></label>
                <input type="number" min="0" asp-for="ToAmount" class="form-control" />
                <span asp-validation-for="ToAmount" class="text-danger"></span>
            </div>
            <div class="col-md-2 form-group-lg">
                <label asp-for="UpToInfinity"></label>
                <input id="isInfinite" type="checkbox" asp-for="UpToInfinity" onchange="SetToAmountInfiniteValue()" />
            </div>
            <br />
            <div>
                <div class="col-md-12 form-group-lg">
                    <label asp-for="CalcMethodList"></label>
                    @Html.DropDownList("selectedMethod", Model.CalcMethodList, new { @class = "form-control" })
                    <span asp-validation-for="CalcMethodList" class="text-danger"></span>
                </div>
                <div class="col-md-6 form-group-lg">
                    <label asp-for="SharedValue"></label>
                    <input type="number" min="0" asp-for="SharedValue" step="0.01" title="Введите числовое значение" class="form-control" />
                    <span asp-validation-for="SharedValue" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="col-md-6 form-group-lg">
                <label asp-for="DateOfStart"></label><br />
                <label class="form-control">@Model.DateOfStart.ToShortDateString()</label>
                <input asp-for="DateOfStart" type="hidden" value="@Model.DateOfStart" />
            </div>
        </div>
        <div class="col-md-offset-9 col-md-3" style="margin-top: 15px">
            <button type="submit" class="btn btn-default btn-group-lg">Сохранить запись</button>
        </div>
    </form>
    <hr/>
    <div class="col-md-offset-9 col-md-3" style="margin-top: 30px">
        <button type="submit" class="btn btn-default btn-group-lg" onclick="SendExitFromMaster()">Выйти из мастер-формы</button>
    </div>
</div>
<hr />

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    
    <script>
        function SetToAmountInfiniteValue() {
            if ($('#isInfinite').prop("checked")) {
                $('#toAmountValue').css('visibility', 'hidden');
            }
            else {
                $('#toAmountValue').css('visibility', 'visible');
            }
        }

        function SendExitFromMaster() {
            alert("Чтобы выйти с мастер-формы нужно покрыть весь диапозон");
        }
    </script>
}

Online_wallet_project/Online_wallet_project/Views/Fee/DateOfStartSelect.cshtml
@model Online_wallet_project.Models.SupplierFeeViewModels.DateOfStartSelectViewModel

@{
    ViewBag.Title = "Выбор даты старта для новой записи";
}

<h4>@ViewBag.Title</h4>
<br/>
<div class="col-md-12 row">
    <form asp-action="DateOfStartSelect" asp-controller="Fee" method="post" asp-antiforgery="true">
        <input asp-for="SupplierId" />
        <input asp-for="IsEdited" />
        <input asp-for="MethodToRedirect" />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="col-md-6 form-group-lg">
            <label asp-for="DateOfStart"></label>
            <input asp-for="DateOfStart" class="form-control" />
            <span asp-validation-for="DateOfStart" class="text-danger"></span>
        </div>
        <div class="col-md-offset-5 col-md-7" style="margin-top: 10px">
            <input type="submit" value="Далее" class="btn btn-default btn-group-lg" />
        </div>
    </form>
</div>

Online_wallet_project/Online_wallet_project/Views/Fee/FeeTypeSelect.cshtml
@model Online_wallet_project.Models.SupplierFeeViewModels.SupplierFeeStatusViewModel
@{
    ViewBag.Title = "Настройки комиссии";
}
@Html.Partial("_StatusMessage", Model.Message)

<h3>@ViewBag.Title</h3>

@Html.Partial("SupplierInfo", Model.FeeHistoryModel)
<div>
    <hr />
    <form asp-action="FeeTypeSelect" method="post" asp-antiforgery="true">
        <input asp-for="SupplierId" />
        <input asp-for="IsEdited" />
        <div>
            <div class="form-group-lg">
                <label asp-for="FeeTypeSelectList"></label>
                @Html.DropDownList("feeStatus", Model.FeeTypeSelectList, new { @class = "form-control" })
                <span asp-validation-for="FeeTypeSelectList"></span>
            </div>
            <br />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="col-md-6 form-group-lg">
                <label asp-for="DateOfStart"></label>
                <input asp-for="DateOfStart" class="form-control" />
                <span asp-validation-for="DateOfStart" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="col-md-offset-11 col-md-1">
            <input type="submit" value="Далее" class="btn btn-default btn-group-lg" />
        </div>
    </form>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Online_wallet_project/Online_wallet_project/Views/Fee/FullRangeCoverage.cshtml
@model Online_wallet_project.Models.SupplierFeeViewModels.SupplierFeeHistoryViewModel
@{
    ViewBag.Title = "Выход из мастера";
}
@Html.Partial("SupplierInfo", Model)
<h3>Весь диапазон успешно покрыт</h3>
<br />
<div>
    <a asp-action="SupplierCommissionInfo" asp-controller="Fee" asp-route-supplierId="@Model.Supplier.Id" class="btn btn-default btn-group-lg">
        Выйти из мастер-формы
    </a>
</div>

Online_wallet_project/Online_wallet_project/Views/Fee/SupplierInfo.cshtml
@model Online_wallet_project.Models.SupplierFeeViewModels.SupplierFeeHistoryViewModel
<div>
    <div style="border: 2px solid black; padding: 0 7px">
        <table class="table table-responsive table-striped">
            <tr>
                <th>Имя поставщика</th>
                <th>Макс. сумма платежа</th>
                <th>Статус комиссии на текущий день</th>
            </tr>
            <tr>
                <td>
                    @Model.Supplier.SupplierName
                </td>
                @if (Model.Supplier.AmountOfRestriction >= UInt32.MaxValue)
                {
                    <td>
                        Неограниченна
                    </td>
                }
                else
                {
                    <td>
                        @Model.Supplier.AmountOfRestriction
                    </td>
                }
                @if (Model.FeeStatusName == null)
                {
                    <td>
                        Не установлена
                    </td>
                }
                else
                {
                    <td>
                        @Model.FeeStatusName
                    </td>
                }

            </tr>
        </table>
    </div>
    <hr />
    @if (Model.FeeStatusChanges != null)
    {
        <div style="border: 2px solid black; padding: 0 7px">
            <h4>Изменения в статусах комиссии</h4>
            <table class="table table-responsive table-striped">
                <tr>
                    <th>Дата старта</th>
                    <th>Статус</th>
                    <th>Состояние</th>
                </tr>
                @foreach (var status in Model.FeeStatusChanges)
                {
                    if (status.Id == Model.CurrentFeeStatusId)
                    {
                        <tr style="background-color: yellow">
                            <td>
                                @status.DateOfStart.ToShortDateString()
                            </td>
                            <td>
                                @status.FeeStatus
                            </td>
                            <td>
                                <b>Актуальный</b>
                            </td>
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td>
                                @status.DateOfStart.ToShortDateString()
                            </td>
                            <td>
                                @status.FeeStatus
                            </td>
                            <td>
                                Неактуален
                            </td>
                        </tr>
                    }
                }

            </table>
        </div>
        <hr />
    }
    @if (Model.TurnOverHistory != null)
    {
        <div style="border: 2px solid black;  padding: 0 7px">
            <h4>Доля оператора с оборота при безкомиссионых платежах</h4>
            <table class="table table-striped">
                <tr>
                    <th>Дата старта</th>
                    <th>Сумма с</th>
                    <th>Сумма до</th>
                    <th>Способ подсчета</th>
                    <th>Доля</th>
                    <th>Дата создания</th>
                </tr>
                @foreach (var report in Model.TurnOverHistory)
                {
                    <tr>
                        <td>@report.DateOfStart.ToShortDateString()</td>
                        <td>@report.SumMin</td>
                        @if (report.SumMax >= UInt32.MaxValue)
                        {
                            <td>И выше</td>
                        }
                        else
                        {
                            <td>@report.SumMax</td>
                        }
                        <td>@report.CalculatingMethod</td>
                        <td>@report.SharedValue</td>
                        <td>@report.DateOfCreation</td>
                    </tr>
                }
            </table>
        </div>
        <hr />
    }
    @if (Model.FeePartHistory != null)
    {
        <div style="border: 2px solid black;  padding: 0 7px">
            <h4>Доля оператора при делении комиссии</h4>
            <table class="table table-striped">
                <tr>
                    <th>Дата старта</th>
                    <th>Способ подсчета</th>
                    <th>Доля</th>
                    <th>Дата создания</th>
                </tr>
                @foreach (var report in Model.FeePartHistory)
                {
                    <tr>
                        <td>@report.DateOfStart.ToShortDateString()</td>
                        <td>@report.CalculatingMethod</td>
                        <td>@report.SharedValue</td>
                        <td>@report.DateOfCreation</td>
                    </tr>
                }
            </table>
        </div>
        <hr />
    }
    @if (Model.FeePaidByUserHistory != null)
    {
        <div style="border: 2px solid black; padding: 0 7px">
            <h4>Комиссия взимаемая с клиентов поставщика</h4>
            <table class="table table-striped">
                <tr>
                    <th>Дата старта</th>
                    <th>Сумма с</th>
                    <th>Сумма до</th>
                    <th>Способ подсчета</th>
                    <th>Комиссия</th>
                    <th>Дата создания</th>
                </tr>
                @foreach (var report in Model.FeePaidByUserHistory)
                {
                    <tr>
                        <td>@report.DateOfStart.ToShortDateString()</td>
                        <td>@report.SumMin</td>
                        @if (report.SumMax >= UInt32.MaxValue)
                        {
                            <td>И выше</td>
                        }
                        else
                        {
                            <td>@report.SumMax</td>
                        }
                        <td>@report.CalculatingMethod</td>
                        <td>@report.FeeValue</td>
                        <td>@report.DateOfCreation</td>
                    </tr>
                }
            </table>
        </div>
    }
</div>

Online_wallet_project/Online_wallet_project/Views/Fee/_Layout.cshtml
@using Online_wallet_project.Models.SupplierFeeViewModels

@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Мастер-форма по настройке комисcии поставщика";
}

<h2>@ViewBag.Title</h2>
<div>
    <br/>
    <div class="row">
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
}